// Item (video row) mutations — client-callable. Ids are generated by the
// caller so optimistic state and the database row always agree. Deletes are
// soft (deleted_at) so the week-2 trash can restore them (N6).

import type { BrowserClient } from "@/lib/supabase/client";

export async function insertItem(
  supabase: BrowserClient,
  params: {
    id: string;
    boardId: string;
    groupId: string;
    name: string;
    position: string;
    userId: string;
  },
): Promise<void> {
  const { error } = await supabase.from("items").insert({
    id: params.id,
    board_id: params.boardId,
    group_id: params.groupId,
    name: params.name,
    position: params.position,
    created_by: params.userId,
  });
  if (error) throw new Error(`Kunne ikke opprette videoen: ${error.message}`);
}

export async function renameItem(
  supabase: BrowserClient,
  params: { boardId: string; itemId: string; name: string },
): Promise<void> {
  const { error } = await supabase
    .from("items")
    .update({ name: params.name })
    .eq("id", params.itemId)
    .eq("board_id", params.boardId);
  if (error) throw new Error(`Kunne ikke endre navnet: ${error.message}`);
}

export async function moveItem(
  supabase: BrowserClient,
  params: { boardId: string; itemId: string; position: string },
): Promise<void> {
  const { error } = await supabase
    .from("items")
    .update({ position: params.position })
    .eq("id", params.itemId)
    .eq("board_id", params.boardId);
  if (error) throw new Error(`Kunne ikke flytte videoen: ${error.message}`);
}

export async function softDeleteItem(
  supabase: BrowserClient,
  params: { boardId: string; itemId: string },
): Promise<void> {
  const { error } = await supabase
    .from("items")
    .update({ deleted_at: new Date().toISOString() })
    .eq("id", params.itemId)
    .eq("board_id", params.boardId);
  if (error) throw new Error(`Kunne ikke slette videoen: ${error.message}`);
}
